### ISSUE TITLE
Bug | Position of 'X mins read' on Mobile screen

### ISSUE THREAD

**Issue by aadeshkulkarni** [aadeshkulkarni/medium-app#169]
### Where ?

- User opens the app on mobile screen
- User goes to a blog which has tags
- At the bottom, the tags and 'X mins read' are on different lines.

### What ?
- At the bottom, the tags and 'X mins read' could be on the same line.

### Reasoning:
- The 'X mins read' is sometimes not visible on some mobile screens. Received this feedback from users.

### Screenshot:

![Screenshot 2024-06-13 at 10 38 16 AM](https://github.com/aadeshkulkarni/medium-app/assets/67855887/efe08e85-5e0b-471e-b3a0-977dc868b285)

**Comment by moiam** [comment]
Hey @aadeshkulkarni , I would like to take this task.

**Comment by aadeshkulkarni** [comment]
Sure, assigned it to you.

**Comment by moiam** [comment]
I have solved the x min read position problem. For the visibility issue, if you mean that the green button doesn't let you read x min read, then in order not to modify the position of the button I would add less opacity, so that you can see through it, as I show in this picture:
![button visibility](https://github.com/aadeshkulkarni/medium-app/assets/169160924/9834788e-aa51-4af6-b8e6-e3043945456f)
